import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../assets/scss/main.scss";
import "../assets/scss/library/style.scss";
import "./globals.css";

import Header from "@/components/user/layout/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1 maximum-scale=1.0, user-scalable=no" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <Header />
      <div className="px-5">
        {children}
      </div>

      </body>
    </html>
  );
}
